/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoFormRouteImport } from './routes/demo.form'
import { Route as DashSidebarRouteImport } from './routes/dash/_sidebar'
import { Route as DashSidebarTestRouteImport } from './routes/dash/_sidebar/test'
import { Route as DashSidebarAuthRouteImport } from './routes/dash/_sidebar/auth'
import { Route as DashSidebarUnitsRouteRouteImport } from './routes/dash/_sidebar/units/route'
import { Route as DashSidebarSubjectsRouteRouteImport } from './routes/dash/_sidebar/subjects/route'
import { Route as DashSidebarLessonsRouteRouteImport } from './routes/dash/_sidebar/lessons/route'

const DashRouteImport = createFileRoute('/dash')()

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSidebarRoute = DashSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => DashRoute,
} as any)
const DashSidebarTestRoute = DashSidebarTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => DashSidebarRoute,
} as any)
const DashSidebarAuthRoute = DashSidebarAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DashSidebarRoute,
} as any)
const DashSidebarUnitsRouteRoute = DashSidebarUnitsRouteRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DashSidebarRoute,
} as any)
const DashSidebarSubjectsRouteRoute =
  DashSidebarSubjectsRouteRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => DashSidebarRoute,
  } as any)
const DashSidebarLessonsRouteRoute = DashSidebarLessonsRouteRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => DashSidebarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashSidebarRouteWithChildren
  '/demo/form': typeof DemoFormRoute
  '/dash/lessons': typeof DashSidebarLessonsRouteRoute
  '/dash/subjects': typeof DashSidebarSubjectsRouteRoute
  '/dash/units': typeof DashSidebarUnitsRouteRoute
  '/dash/auth': typeof DashSidebarAuthRoute
  '/dash/test': typeof DashSidebarTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash': typeof DashSidebarRouteWithChildren
  '/demo/form': typeof DemoFormRoute
  '/dash/lessons': typeof DashSidebarLessonsRouteRoute
  '/dash/subjects': typeof DashSidebarSubjectsRouteRoute
  '/dash/units': typeof DashSidebarUnitsRouteRoute
  '/dash/auth': typeof DashSidebarAuthRoute
  '/dash/test': typeof DashSidebarTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/dash/_sidebar': typeof DashSidebarRouteWithChildren
  '/demo/form': typeof DemoFormRoute
  '/dash/_sidebar/lessons': typeof DashSidebarLessonsRouteRoute
  '/dash/_sidebar/subjects': typeof DashSidebarSubjectsRouteRoute
  '/dash/_sidebar/units': typeof DashSidebarUnitsRouteRoute
  '/dash/_sidebar/auth': typeof DashSidebarAuthRoute
  '/dash/_sidebar/test': typeof DashSidebarTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/demo/form'
    | '/dash/lessons'
    | '/dash/subjects'
    | '/dash/units'
    | '/dash/auth'
    | '/dash/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash'
    | '/demo/form'
    | '/dash/lessons'
    | '/dash/subjects'
    | '/dash/units'
    | '/dash/auth'
    | '/dash/test'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/dash/_sidebar'
    | '/demo/form'
    | '/dash/_sidebar/lessons'
    | '/dash/_sidebar/subjects'
    | '/dash/_sidebar/units'
    | '/dash/_sidebar/auth'
    | '/dash/_sidebar/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  DemoFormRoute: typeof DemoFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/_sidebar': {
      id: '/dash/_sidebar'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashSidebarRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/_sidebar/test': {
      id: '/dash/_sidebar/test'
      path: '/test'
      fullPath: '/dash/test'
      preLoaderRoute: typeof DashSidebarTestRouteImport
      parentRoute: typeof DashSidebarRoute
    }
    '/dash/_sidebar/auth': {
      id: '/dash/_sidebar/auth'
      path: '/auth'
      fullPath: '/dash/auth'
      preLoaderRoute: typeof DashSidebarAuthRouteImport
      parentRoute: typeof DashSidebarRoute
    }
    '/dash/_sidebar/units': {
      id: '/dash/_sidebar/units'
      path: '/units'
      fullPath: '/dash/units'
      preLoaderRoute: typeof DashSidebarUnitsRouteRouteImport
      parentRoute: typeof DashSidebarRoute
    }
    '/dash/_sidebar/subjects': {
      id: '/dash/_sidebar/subjects'
      path: '/subjects'
      fullPath: '/dash/subjects'
      preLoaderRoute: typeof DashSidebarSubjectsRouteRouteImport
      parentRoute: typeof DashSidebarRoute
    }
    '/dash/_sidebar/lessons': {
      id: '/dash/_sidebar/lessons'
      path: '/lessons'
      fullPath: '/dash/lessons'
      preLoaderRoute: typeof DashSidebarLessonsRouteRouteImport
      parentRoute: typeof DashSidebarRoute
    }
  }
}

interface DashSidebarRouteChildren {
  DashSidebarLessonsRouteRoute: typeof DashSidebarLessonsRouteRoute
  DashSidebarSubjectsRouteRoute: typeof DashSidebarSubjectsRouteRoute
  DashSidebarUnitsRouteRoute: typeof DashSidebarUnitsRouteRoute
  DashSidebarAuthRoute: typeof DashSidebarAuthRoute
  DashSidebarTestRoute: typeof DashSidebarTestRoute
}

const DashSidebarRouteChildren: DashSidebarRouteChildren = {
  DashSidebarLessonsRouteRoute: DashSidebarLessonsRouteRoute,
  DashSidebarSubjectsRouteRoute: DashSidebarSubjectsRouteRoute,
  DashSidebarUnitsRouteRoute: DashSidebarUnitsRouteRoute,
  DashSidebarAuthRoute: DashSidebarAuthRoute,
  DashSidebarTestRoute: DashSidebarTestRoute,
}

const DashSidebarRouteWithChildren = DashSidebarRoute._addFileChildren(
  DashSidebarRouteChildren,
)

interface DashRouteChildren {
  DashSidebarRoute: typeof DashSidebarRouteWithChildren
}

const DashRouteChildren: DashRouteChildren = {
  DashSidebarRoute: DashSidebarRouteWithChildren,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  DemoFormRoute: DemoFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
